# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08f1eb2b307461493d665a224bf6120448436cf6455807db22d74b87a1b7e2a40fbb4df7783bf7c7caf2b793482e464f2fd83fc74f189b6c550388130b2a8d49

test:
  secret_key_base: 6c89465cf0aa65b7ecd7e385ee00c339aecadea39414fc1cc951089fbed49ff4610c831ee68d45b7e04366d68e15a540c1bbf7a6d8f590ad2b321cff48b088df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
